### ISSUE TITLE
Get secret key

### ISSUE THREAD

**Issue by Raggaer** [sec51/twofactor#2]
I need to communicate with another service so I need to store the secret key on a database. the raw Base32 alphabet one without encryption

I know this is not the best aproach but still.

Is there a way to get the secret key without the encryption layers?

Thanks

**Comment by silenteh** [comment]
@Raggaer 
Yep it's definitely not the best approach...
The idea behind this library is to try to offer security out of the box, without the user having to deal with it.
I understand, however, that there are situations where, unfortunately, this can cause interoperability problems with other technologies.

Quick question: is the other service also based on Golang ?
If yes, then there is way to share the private keys between different services or even servers.
If not then, I can take a look on how complicated it would be to allow a private key to be stored without being encrypted.

**Comment by silenteh** [comment]
@Raggaer 
I haven't heard anything back so far, therefore I am going ahead and closing this one down.
In case you need further help, please open a new issue.
Thanks
